### ISSUE TITLE
Include Python in environment for `yarn install`

### ISSUE THREAD

**Issue by vpontis** [Borales/actions-yarn#13]
@Borales, thank you for this action!

I get an error when installing `pg-native` which depends on `libpq`. `libpq` wants Python to be available and it can't find the Python installation. 

How should I go about fixing this issue? 

Do I need to create a separate action which has a `Dockerfile` that also includes `python`? Or can this action somehow pick up the machine's native Python installation?

---

```
error /github/workspace/server/node_modules/libpq: Command failed.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /github/workspace/server/node_modules/libpq
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.16.3 | linux | x64
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
```

**Comment by Borales** [comment]
@vpontis hi
I think in your case - you might think of using `setup-*` actions (https://github.com/actions/setup-python):

```
steps:
- uses: actions/checkout@master
- uses: actions/setup-python@v1
  with:
    python-version: '3.x'
    architecture: 'x64'
- uses: actions/setup-node@v1
  with:
    node-version: '10'
- run: yarn install
```

**Comment by vpontis** [comment]
Awesome thanks @Borales 

I ended up doing this to get it working:

```
  server_tests:
    name: Server Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install Postgres
        run: |
          sudo apt-get install postgresql postgresql-contrib libpq-dev
      - uses: actions/setup-node@v1
        with:
          node-version: '10'
      - run: yarn --cwd server install
      - run: yarn --cwd server test
```

@Borales when would someone use this repo's `actions-yarn` step rather than `setup-node`?
