### ISSUE TITLE
Files created as root user

### ISSUE THREAD

**Issue by mintuz** [Borales/actions-yarn#14]
Hello I have noticed that when I use the action to install and build my project artefacts that they are created with root user. I believe this has a knock on affect with actions defined after yarn. I have attached a screenshot 

You can see my workflow here.

```
name: Build and Deploy Storybook
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy-documentation:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Install
              uses: Borales/actions-yarn@v2.0.1
              with:
                  cmd: install
            - name: Build
              uses: Borales/actions-yarn@v2.0.1
              with:
                  cmd: build-storybook
            - name: Display Workspace
              run: ls -la
              shell: bash
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v2.5.0
              env:
                  PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  PUBLISH_BRANCH: gh-pages
                  PUBLISH_DIR: ./storybook-static
```

![Screenshot 2019-10-30 at 19 53 01](https://user-images.githubusercontent.com/447031/67893764-1e3fda00-fb4f-11e9-8cd4-01b62fb63135.png)
