### ISSUE TITLE
Support to all virtual environments

### ISSUE THREAD

**Issue by marceloogeda** [Borales/actions-yarn#22]
Currently, it's only supported in the Linux environment.

I tried to run this action on macOS environment and got the following error message:

```sh
Run borales/actions-yarn@v2.0.0
##[error]Container action is only supported on Linux
```

**Comment by Borales** [comment]
@marceloogeda how exactly did you run it?

**Comment by marceloogeda** [comment]
@Borales, this is how my job configuration looks like:

```yaml
...

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Read .nvmrc file
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

...
```
