### ISSUE TITLE
Multiple args?

### ISSUE THREAD

**Issue by guaiamum** [Borales/actions-yarn#23]
Hey, couldn't find if there's a way to use multiple `cmd` in the same `uses`, like this:
```
uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: install,test
```
So I don't have to repeat the `uses`

**Comment by oscarmorrison** [comment]
Is this possible @Borales

**Comment by Borales** [comment]
@guaiamum @oscarmorrison I'm afraid not, usually, Github Actions uses 1 command per `uses` block.

**Comment by Borales** [comment]
so something like this:

```
uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: install
uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: test
```
