### ISSUE TITLE
Error when adding a dependency from GitHub

### ISSUE THREAD

**Issue by dcangulo** [Borales/actions-yarn#30]
When using `npm` (works perfectly):
```yml
name: eslint
on: [push, pull_request]
jobs:
  tap:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint
```

When using `actions-yarn` (doesn't work):
```yml
name: eslint
on: [push, pull_request]
jobs:
  tap:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Run linter
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint
```

Error logs:
```
Run borales/actions-yarn@v2.0.0
yarn install v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Sample `package.json`: 
```json
{
  "name": "sample-package-json",
  "scripts": {
    "lint": "eslint ."
  },
  "dependencies": {
    "our-secret-package": "git+https://[TOKEN]:x-oauth-basic@github.com/org/our-secret-package.git",
  }
}
```
