### ISSUE TITLE
Document used yarn version?

### ISSUE THREAD

**Issue by ChristopherJTrent** [Borales/actions-yarn#301]
I have a project using yarn 4, It'd be extremely helpful if this package documented which version of yarn it used.

**Comment by Borales** [comment]
Added a note in README

**Comment by Niek** [comment]
Changing to this worked for me:
```yaml
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: yarn
      - run: yarn install --immutable
```
