### ISSUE TITLE
Run in specific folder

### ISSUE THREAD

**Issue by awalshy** [Borales/actions-yarn#31]
### Run the yarn command in a workspace's folder
Here is a usecase example.
Repo Architecture:
```
.
frontend
_ package.json
backend
```

Would run the yarn command in the selected folder (frontend|backend)
```yaml
- name: Install dependencies
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
        dir: frontend
```
