### ISSUE TITLE
CI fails due to Node version: The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by Hiroki111** [Borales/actions-yarn#41]
In `package.json`, I have:

```
  "engines": {
    "yarn": "1.22.10",
    "node": "12.21.0"
  }
```

In the CI config (`.github/workflows/push.yml`):

```
jobs:
  lint-test:
    name: lint test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'

      - name: Install npm packages
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
```
At `Install npm packages`, I got the following message:

```
yarn install v1.22.10
[1/5] Validating package.json...
error booking@1.0.0: The engine "node" is incompatible with this module. Expected version "12.21.0". Got "16.13.0"
error Found incompatible module.
```

Is this an issue with `actions/setup-node`?
