### ISSUE TITLE
Not finding build:prod

### ISSUE THREAD

**Issue by varndellwagglebee** [Borales/actions-yarn#68]
Error:
```
Run Borales/actions-yarn@v4.2.0
/usr/local/bin/yarn build:prod "set \"GENERATE_SOURCEMAP=false\" && react-scripts build"
yarn run v[1](https://github.com/Stillpoint-Software/wagglebee.ui/actions/runs/3651200718/jobs/6168130627#step:7:1).22.19
error Command "build:prod" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: The process '/usr/local/bin/yarn' failed with exit code 1
```

Job steps:
```
build_and_deploy_job:
  
    runs-on: ubuntu-latest
    name: Test and Build     
    steps:
      - name: directory
        run: echo ${{ env.DEFAULT-REPOSITORY }}
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path:  ${{ env.DEFAULT-REPOSITORY }}
        
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x
          cache: 'yarn'
          cache-dependency-path: ${{ env.DEFAULT-REPOSITORY }}
        
      - name: Run Yarn install
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: install # will run `yarn install` command
          dir: ${{ env.DEFAULT-REPOSITORY }}
                    
      - name: Build production bundle
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: build:prod "set \"GENERATE_SOURCEMAP=false\" && react-scripts build"  # will run `yarn build:prod  command
          dir: ${{ env.DEFAULT-REPOSITORY }}

```

PROJECT Structure:

software/waggle/website

The yarn lock file and the package.json file are in the "WEBSITE sub folder.

**Comment by Borales** [comment]
@varndellwagglebee does it work for you locally? 
`yarn build:prod "set \"GENERATE_SOURCEMAP=false\" && react-scripts build"`?

I checked a sub-folder command - it works fine. I think it's something with the command syntax itself

**Comment by varndellwagglebee** [comment]
Yes, I can run yarn run build:prod locally.

**Comment by Borales** [comment]
@varndellwagglebee with the rest of it? you posted `cmd: build:prod "set \"GENERATE_SOURCEMAP=false\" && react-scripts build"` as you command.

**Comment by varndellwagglebee** [comment]
Yes,   This is the script for build:prod 
 "build:prod": "set \"GENERATE_SOURCEMAP=false\" && react-scripts build",

**Comment by Borales** [comment]
@varndellwagglebee ok, then you have an error in your yml file above. It has to be `cmd: build:prod`

**Comment by varndellwagglebee** [comment]
I've tried build:prod and get the same error

**Comment by Borales** [comment]
@varndellwagglebee then double-check if you really get the value in `dir: ${{ env.DEFAULT-REPOSITORY }}`.

I checked the sub-folder commands - they work

**Comment by varndellwagglebee** [comment]
Still Error: error Command "build:prod" not found.

```
Run Borales/actions-yarn@v4.[2](https://github.com/Stillpoint-Software/wagglebee.ui/actions/runs/3651563665/jobs/6168916613#step:7:2).0
  with:
    cmd: build:prod
    dir: Stillpoint-Software/wagglebee.ui/packages/stillpoint-website
  env:
    AZURE_STATIC_WEB_APPS_API_TOKEN: ***
    APP_LOCATION: packages/stillpoint-website/
    APP_ARTIFACT_LOCATION: packages/stillpoint-website/build
    BRANCH_NAME: develop
    LPOINT: ***
    DEFAULT-REPOSITORY: Stillpoint-Software/wagglebee.ui/packages/stillpoint-website
```
