### ISSUE TITLE
Error: Unable to resolve action `Borales/actions-yarn@4`, unable to find version `4`

### ISSUE THREAD

**Issue by yingshaoxo** [Borales/actions-yarn#73]
Error:

```
Error: Unable to resolve action `Borales/actions-yarn@4`, unable to find version `4`
```

___

The following is working:

```yaml
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v1

      - name: yarn install
        run: yarn install

      - name: yarn build
        run: yarn build 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./dist
```

**Comment by ahf90** [comment]
This also started happening to me. I changed it from:

`uses: borales/actions-yarn@v4`
to
`uses: borales/actions-yarn@v4.2.0`

And the action started working again.

**Comment by yingshaoxo** [comment]
Then you should update the code in the readme file.

If you are busy, I could do it for you.

**Comment by Borales** [comment]
I've been using it as `uses: borales/actions-yarn@v4` with no problems at all.

Could you please double-check your yml file?

<img width="397" alt="Screenshot 2022-12-21 at 12 48 08" src="https://user-images.githubusercontent.com/1118933/208898484-8f335e51-42ca-4535-8be6-58b16be91162.png">

**Comment by Porkepix** [comment]
@Borales Just encountered a very similar issue (though it complains about about type, not about not finding the tag). I'm just starting to work with GitHub Actions and haven't put them online on the repos yet, I instead use https://github.com/nektos/act so I can't tell if it's an effect of it, but simply copying and pasting the example from the README results in the same kind of errors:

```
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
```

Results in this in debug mode:

```
[GitHub Actions Demo/unit_tests]   ☁  git clone 'https://github.com/borales/actions-yarn' # ref=v4
[GitHub Actions Demo/unit_tests] Unable to resolve v4: unsupported object type
[GitHub Actions Demo/unit_tests] Unable to resolve v4: unsupported object type
[GitHub Actions Demo/unit_tests] unsupported object type
[GitHub Actions Demo/unit_tests]   ☁  git clone 'https://github.com/borales/actions-yarn' # ref=v4
[GitHub Actions Demo/unit_tests] Unable to resolve v4: unsupported object type
[GitHub Actions Demo/unit_tests] Unable to resolve v4: unsupported object type
[GitHub Actions Demo/unit_tests] unsupported object type
```

And changing the tag to `4.2.0` have things work correctly.

I searched for similar issues and crossed this: https://github.com/actions/checkout/issues/1042 (same error, but no such issue in your repo - found out through https://github.com/nektos/act/issues/1508); doesn't seems to be what the problem here could be.
I also tried to give a look to the tool's code (though I don't know much about Go) and didn't find anything that could explain this).

The issue is very strange, considering the `v4` tag really points out to the exact same commit as `v4.2.0` tag, and other actions such as `checkout` or `setup-node` gets no such issue.

Any idea, or mind giving a try at `act`, just to rule out it'd come from the tool? Also sorry if you consider this is a completely different issue, I can open another one if you feel so.
