### ISSUE TITLE
Unable to resolve v4

### ISSUE THREAD

**Issue by cristianbote** [Borales/actions-yarn#90]
Hey @Borales,

Tried the action for the first time toady and I am running into errors with `v4` -- apparently. This is my action config:

```yml
name: name

on: deployment_status

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            
            - name: Set Node.js 18.x
              uses: actions/setup-node@v3
              with:
                node-version: 18.x

            - name: Run install
              uses: borales/actions-yarn@v3
              with:
                cmd: install
```

```sh
[name/tests]   ☁  git clone 'https://github.com/borales/actions-yarn' # ref=v4
[name/tests] Unable to resolve v4: unsupported object type
```

**Comment by zyguy-ankorstore** [comment]
Hi @cristianbote, 
You can use the release 4.2.0 instead of 4.

```yaml
  - name: Run install
    uses: borales/actions-yarn@v4.2.0
    with:
      cmd: install # will run `yarn install` command
  - name: Run TypeScript compiler
    uses: borales/actions-yarn@v4.2.0
    with:
      cmd: tsc # will run `yarn tsc` command
  - name: Build backend bundle
    uses: borales/actions-yarn@v4.2.0
    with:
      cmd: build:backend # will run `yarn build:backend` command
```
